# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9840e78e6e54af7ee5de88b4e690c57f42a810e830f41b68bde7deb50d21192e13dcfeba3cf2565611eaaeb6cf9f5e581b7ff8353f8aa0b4f8f425e9fd1dc42

test:
  secret_key_base: edb04008e64b0cc4f5e4c4718a8ef52b61d49e0705d3b1145aeef720ba47b179c4ddc3f3f934276225cdea51581a1bd540c5edcf964979cadd4b218f2b9c7d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
